FROM python:3.12-alpine3.19
# update apk repo
# RUN echo "ipv6" >> /etc/modules
# RUN echo "http://dl-1.alpinelinux.org/alpine/latest-stable/main" >> /etc/apk/repositories \
#     echo "http://dl-2.alpinelinux.org/alpine/latest-stable/main" >> /etc/apk/repositories \
#     echo "http://dl-3.alpinelinux.org/alpine/latest-stable/main" >> /etc/apk/repositories \
#     echo "http://dl-4.alpinelinux.org/alpine/latest-stable/main" >> /etc/apk/repositories \
#     echo "http://dl-5.alpinelinux.org/alpine/latest-stable/main" >> /etc/apk/repositories \
RUN   echo "https://dl-cdn.alpinelinux.org/alpine/v3.19/community" >> /etc/apk/repositories

# install chromedriver
RUN apk update
RUN apk add --no-cache chromium chromium-chromedriver tzdata

# Get all the prereqs
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-2.35-r1.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-bin-2.35-r1.apk

RUN apk update && \
    apk add openjdk11-jre curl tar && \
    curl -o allure-2.27.0.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.tgz && \
    tar -zxvf allure-2.27.0.tgz -C /opt/ && \
    ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure && \
    rm allure-2.27.0.tgz

WORKDIR /usr/workspace

# Copy the dependencies file to the working directory
COPY ./requirements.txt /usr/workspace

# Install Python dependencies
RUN pip3 install -r requirements.txt
