version: '3.8'

services:
  regression:
    image: python:3.12-alpine3.19
    build:
      context: .
      dockerfile: Dockerfile.txt
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results $TEST_ARGS"
    working_dir: /usr/workspace
    environment:
      - USER_LOGIN=${USER_LOGIN}
      - USER_PASSWORD=${USER_PASSWORD}
      - TEST_ARGS=${TEST_ARGS}
